sever:
  port: 8082
  servlet:
    context:
      path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker
    username: root
    password: dbwnqhd
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
jwt:
  secret: b2tech
